apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: host-info-srv-config
  namespace: operator-test
spec:
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: envoy.http_connection_manager
              subFilter:
                name: envoy.router
      patch:
        operation: INSERT_BEFORE
        value:
          config:
            domain: host-info
            failure_mode_deny: false
            rate_limit_service:
              grpc_service:
                envoy_grpc:
                  cluster_name: patched.rate-limiter.operator-test.svc.cluster.local
                timeout: 0.25s
          name: envoy.rate_limit
    - applyTo: CLUSTER
      match:
        cluster:
          service: rate-limiter.operator-test.svc.cluster.local
      patch:
        operation: MERGE
        value:
          name: patched.rate-limiter.operator-test.svc.cluster.local
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: 'host-info-srv.org:80'
            route: {}
      patch:
        operation: MERGE
        value:
          rate_limits:
            - actions:
                - request_headers:
                    descriptor_key: custom-rl-header
                    header_name: custom-rl-header
  workloadSelector:
    labels:
      istio: ingressgateway