apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ratelimiterconfigs.operators.example.com
spec:
  group: operators.example.com
  names:
    kind: RateLimiterConfig
    listKind: RateLimiterConfigList
    plural: ratelimiterconfigs
    singular: ratelimiterconfig
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: RateLimiterConfig is the Schema for the ratelimiterconfigs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              applyTo:
                enum:
                - GATEWAY
                - SIDECAR_INBOUND
                - SIDECAR_OUTBOUND
                type: string
              failureModeDeny:
                type: boolean
              host:
                maxLength: 255
                minLength: 1
                type: string
              port:
                format: int32
                maximum: 65535
                minimum: 0
                type: integer
              rateLimitProperty:
                properties:
                  descriptors:
                    items:
                      properties:
                        descriptors:
                          items:
                            properties:
                              key:
                                maxLength: 255
                                minLength: 1
                                type: string
                              rate_limit:
                                properties:
                                  requests_per_unit:
                                    format: int32
                                    minimum: 0
                                    type: integer
                                  unit:
                                    enum:
                                    - second
                                    - minute
                                    - hour
                                    - day
                                    type: string
                                required:
                                - requests_per_unit
                                - unit
                                type: object
                              value:
                                maxLength: 255
                                minLength: 1
                                type: string
                            required:
                            - key
                            type: object
                          type: array
                        key:
                          maxLength: 255
                          minLength: 1
                          type: string
                        rate_limit:
                          properties:
                            requests_per_unit:
                              format: int32
                              minimum: 0
                              type: integer
                            unit:
                              enum:
                              - second
                              - minute
                              - hour
                              - day
                              type: string
                          required:
                          - requests_per_unit
                          - unit
                          type: object
                        value:
                          maxLength: 255
                          minLength: 1
                          type: string
                      required:
                      - key
                      type: object
                    type: array
                  domain:
                    maxLength: 255
                    minLength: 4
                    type: string
                required:
                - domain
                type: object
              rateLimitRequestTimeout:
                pattern: ^([0-9]+(\.[0-9]+)?(ms|s|m|h))+$
                type: string
              rateLimiter:
                maxLength: 255
                minLength: 1
                type: string
              workloadSelector:
                properties:
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - labels
                type: object
            required:
            - applyTo
            - port
            - rateLimiter
            - workloadSelector
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
