apiVersion: operators.example.com/v1
kind: RateLimiterConfig
metadata:
  name: host-info-srv-config
  namespace: operator-test
spec:
  rateLimiter: "rate-limiter"
  failureModeDeny: false
  virtualHostName: "host-info-srv.org:80"
  rateLimitProperty:
    domain: host-info
    descriptors:
      - key: custom-rl-header
        value: setting1
        rate_limit:
          unit: minute
          requests_per_unit: 1
