apiVersion: operators.example.com/v1
kind: RateLimitConfig
metadata:
  name: ratelimit-config
spec:
  rateLimiter: "rate-limiter"
  failureModeDeny: true
  virtualHostName: "host-info-service.org:80"
  rateLimitProperty:
    domain: test
    descriptors:
      - key: custom-rl-header
        value: setting1
        rate_limit:
          unit: minute
          requests_per_unit: 1
