kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ratelimit-operator
subjects:
- kind: ServiceAccount
  name: ratelimit-operator
  #namespace: operator-test
roleRef:
  kind: ClusterRole
  name: ratelimit-operator
  apiGroup: rbac.authorization.k8s.io
